### ISSUE TITLE
Value cannot be null error.

### ISSUE THREAD

**Issue by syaheer** [bunzosteele/PokeWatch#34]
Hi,

I am getting this error after awhile.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Pokewatch.Program.SpellCheckPokemon(PokemonId pokemon, Boolean isHashtag) in C:\Code\PokeWatch\Pokewatch\Program.cs:line 297
   at Pokewatch.Program.ComposeTweet(FoundPokemon pokemon, Region region) in C:\Code\PokeWatch\Pokewatch\Program.cs:line 249
   at Pokewatch.Program.Search() in C:\Code\PokeWatch\Pokewatch\Program.cs:line 99
   at Pokewatch.Program.Main(String[] args) in C:\Code\PokeWatch\Pokewatch\Program.cs:line 56

May I know if there is something wrong with my configuration file?

**Comment by bunzosteele** [comment]
You probably deleted one of the fields from Configuration.json that you thought you didnt need, this ideally wouldnt crash the app, but currently is. Perhapes the PokemonOverrides?

**Comment by syaheer** [comment]
you're right I dont have that in my configuration file. I am adding it back in and see if the crash is still happening.

**Comment by syaheer** [comment]
Problem solved. Thanks!
