### ISSUE TITLE
Pokewatch crashes

### ISSUE THREAD

**Issue by omniraven** [bunzosteele/PokeWatch#48]
[log.txt](https://github.com/bunzosteele/PokeWatch/files/391363/log.txt)
Not sure why, but this happens extremely often. It will be running and it will shut down and restart in 2 minutes without processing anything. Log just says "something went wrong at x/xx/xxxx x:xx am/pm. Waiting 2 minutes to restart." Is this normal? or is it server side? For instance, the last 3 times in closed immediately after opening.

**Comment by bunzosteele** [comment]
That looks like the servers going down and it repeatedly trying to reconnect

**Comment by RedSparr0w** [comment]
~~if my internet goes out i get a popup saying "Demo has crashed" and the command window stays open until i acknowledge the message, so program does not restart.~~

~~Is there any way for it to fail silently?~~ 

~~and in the command prompt i get the following error:~~

``` cmd
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'pgorelease.nianticlabs.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at POGOLib.Net.RpcClient.SendRemoteProcedureCall(Request request) in C:\Code\POGOLib\POGOLib\Net\RpcClient.cs:line 234
   at POGOLib.Net.RpcClient.RefreshMapObjects() in C:\Code\POGOLib\POGOLib\Net\RpcClient.cs:line 80
   at POGOLib.Pokemon.HeartbeatDispatcher.Dispatch() in C:\Code\POGOLib\POGOLib\Pokemon\HeartbeatDispatcher.cs:line 89
   at POGOLib.Pokemon.HeartbeatDispatcher.CheckDispatch() in C:\Code\POGOLib\POGOLib\Pokemon\HeartbeatDispatcher.cs:line 81
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Edit: Just saw it in the README
