### ISSUE TITLE
Unhandled Issue Caused Crash

### ISSUE THREAD

**Issue by Pallaxis** [bunzosteele/PokeWatch#6]
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
   at POGOLib.Net.RpcClient.GetMapObjects()
   at POGOLib.Net.RpcClient.Heartbeat()
   at POGOLib.Net.PoClient.<StartHeartbeats>b__45_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by bunzosteele** [comment]
This crash occurs whenever the app loses connection with the server, you can follow this step from the optional section of the readme to allow the bot to reboot itself and continue running, without any intervention on your part:
b. PokewatchLauncher.exe will restart pokewatch any time it dies in the middle of running (usually due to server outages). By default on most machines, OS will prompt you to acknowlege the crash before PokewatchLauncher, can reset the application, to disable this and allow the app to run indefinitely without supervision, follow this guide: https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/

**Comment by mle-ii** [comment]
I started playing with this a bit but had other things to do.  :)  I think we might be able to catch and better handle this via an AppDomain Unhandled Exception handler, but I didn't do anything beyond the code below to see if we could in the very least catch it.  Also, might updating the client code that you're using in the lib help?  I think it was an older version when I looked but didn't try that either.

```
		static void MyHandler(object sender, UnhandledExceptionEventArgs args)
		{
			Exception e = (Exception)args.ExceptionObject;
			Console.WriteLine("MyHandler caught : " + e.Message);
			Console.WriteLine("Runtime terminating: {0}", args.IsTerminating);
		}

		public static void Main(string[] args)
		{
			AppDomain currentDomain = AppDomain.CurrentDomain;
			currentDomain.UnhandledException += new UnhandledExceptionEventHandler(MyHandler);
```
